[package]
name = "haskell_to_llvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inkwell = { version = "0.5.0", features = ["llvm14-0"] }
regex = "1.11.1"
tree-sitter = "0.24.4"
tree-sitter-haskell = "0.23.1"

[build-dependencies]
cc = "1.2.1"
